/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2017-06-28 00:08:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Personal Finance Dashboard</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/main-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/toastr.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.5.3/datepicker.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand text-center center-block\" href=\"#\">Personal\r\n");
      out.write("\t\t\t\tFinance Dashboard</a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<!-- \t<li><a href=\"home.jsp\"><span class=\"glyphicon glyphicon-home\"></span></a></li> -->\r\n");
      out.write("\t\t\t\t\t<li class=\"active\" id=\"dashboardMenu\"><a href=\"#\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-home\"></span>&nbsp;&nbsp; Dashboard\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"settingsMenu\"><a href=\"preferences.jsp\">Settings</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li id=\"signOut\"><a href=\"#\"><span class=\"glyphicon glyphicon glyphicon-log-out\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</span>Logout</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.nav-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"loading\"></div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\" id=\"dashboardMain\">\r\n");
      out.write("\t\t\t<div id=\"main\" class=\"col-sm-12 main\">\r\n");
      out.write("\t\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<h3>Overview of Finances</h3>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reportSelect\">Select report:</label> <select\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"reportSelect\"></select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group text-right\">\r\n");
      out.write("\t\t\t\t\t\t<label id=\"reportRange\"></label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <button id='runReport' class=\"btn btn-primary center-block\">Run Report</button> -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mainReport\" class=\"col-sm-12 main\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"well\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"text-left\" id='conditionLabel'></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"text-center\">User Reports</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id='addNewPeriod' class=\"btn btn-default btn-sm pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;Add New Period\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"mainTable\" class=\"display\" cellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\twidth=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Pay Period</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Gross Income</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Net Income</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Expenses</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Saved</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"mainDataTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<p id=\"userInfo\" class=\"text-muted\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<div class=\"navbar navbar-default navbar-fixed-bottom footer\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Add Period modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"addPeriodModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"addPeriodModal\" aria-hidden=\"true\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h5 class=\"modal-title\" >Add New Pay Period</h5>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t        </button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t        <form>\r\n");
      out.write("\t          <div class=\"form-group\">\r\n");
      out.write("\t\t          <label for=\"periodSpan\" class=\"form-control-label\">Pay Period Date: </label>\r\n");
      out.write("\t\t            <div class='input-group date'>\r\n");
      out.write("\t\t\t\t\t\t<input type='text' class=\"form-control\" id='periodSpan' /> \r\n");
      out.write("\t\t\t\t\t\t\t<span  class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-calendar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t          <div class=\"form-group\">\r\n");
      out.write("\t            <label for=\"message-text\" class=\"form-control-label\">Message:</label>\r\n");
      out.write("\t            <textarea class=\"form-control\" id=\"message-text\"></textarea>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div class=\"modal-footer\">\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t        <button type=\"button\" id=\"confirmAddPeriod\" class=\"btn btn-primary\">Confirm</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts and dependencies -->\r\n");
      out.write("\t<script src=\"js/scripts/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/scripts/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://www.gstatic.com/firebasejs/4.1.2/firebase.js\"></script>\r\n");
      out.write("\t<script src=\"https://www.gstatic.com/firebasejs/4.1.2/firebase-app.js\"></script>\r\n");
      out.write("\t<script src=\"https://www.gstatic.com/firebasejs/4.1.2/firebase-auth.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://www.gstatic.com/firebasejs/4.1.2/firebase-database.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js\"></script>\r\n");
      out.write("\t<script src=\"//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.5.3/datepicker.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/scripts/toastr.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/firebase/config.js\"></script>\r\n");
      out.write("\t<script src=\"js/Screens/authentication/logout.js\"></script>\r\n");
      out.write("\t<script src=\"js/Screens/dashboard/dashboard.js\"></script>\r\n");
      out.write("\t<script src=\"js/common.js\"></script>\r\n");
      out.write("\t<script src=\"js/confighelper/confighelper.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$('.navbar li').click(function(e) {\r\n");
      out.write("\t    $('.navbar li.active').removeClass('active');\r\n");
      out.write("\t    var $this = $(this);\r\n");
      out.write("\t    if (!$this.hasClass('active')) {\r\n");
      out.write("\t        $this.addClass('active');\r\n");
      out.write("\t    }\r\n");
      out.write("\t    //e.preventDefault();\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
